### ISSUE TITLE
Breaking in Foundry VTT Version 12 Build 328

### ISSUE THREAD

**Issue by RakeshPoluri** [TheEpicSnowWolf/Foundry-VTT-Prettier-Login-Screen#19]
This doesn't work in the latest stable version (Foundry VTT Version 12 Build 328). We are supposed to add the v12 code at the end of the foundry2.css, right?

**Comment by dandln** [comment]
Hi, seems to be working fine on my instance. Are there specific issues with the style or are the changes not showing up at all? Have you tried clearing your browser cache?

![image](https://github.com/dandln/Foundry-VTT-Prettier-Login-Screen/assets/6506715/652ad531-c7e0-4c86-a3c8-f2117a23e4a4)

**Comment by RakeshPoluri** [comment]
It was not working even after I restarted Foundry, but for some reason, it was working when I checked today.
