### ISSUE TITLE
Logo image display using the name of the world for a file name

### ISSUE THREAD

**Issue by apoapostolov** [TheEpicSnowWolf/Foundry-VTT-Prettier-Login-Screen#5]
Since any logo image would make a whole Foundry instance only fit for one system or franchise game, maybe a way to reuse any data from the original log in screen to display different logos, i.e. D&D, PF2 etc.

**Comment by TheEpicSnowWolf** [comment]
This is unfortunately not possible with only CSS. While I agree that it would be nice to display different images depending on the world that is currently loaded, this would likely involve adding or modifying the Foundry JavaScript involved in the login screen, which is out of scope for this simple CSS modification.

If Foundry ever adds support for plugins that load before a world is accessed (and could therefore modify the login screen logic), this would become more feasible.

**Comment by apoapostolov** [comment]
I have spoken with Atro and unfortunately, he is very much against modification of the login screen. This may change in future years.
