### ISSUE TITLE
Problems with css since Foundry VTT 0.8.9

### ISSUE THREAD

**Issue by damdor** [TheEpicSnowWolf/Foundry-VTT-Prettier-Login-Screen#6]
Hi!

First of all thanks for doing this, I love this compared to the default login screen! I recently upgraded my server to 0.8.9, the update always overwrites the old config, so I added your section and configured it like before with a top and footer logo and some custom colors on the buttons. But some of these does not work anymore. 

1. No logos will be displayed
2. Title will be displayed even if it is configured in your CSS section to disable it
3. Buttons are not displayed

These are just some of the main things I noticed after the upgrade.

Kind regards

**Comment by TheEpicSnowWolf** [comment]
Hi @damdor, apologies for the long radio silence! I have just upgraded to 0.8.9 myself and do not have any issues with my same CSS configuration as under 0.8.8. Do other style elements (like the bigger text boxes in a new line) work as intended? Or were you able to resolve the issue in the meantime? Also thanks for the kind words, and sorry again for the delay. :)

**Comment by damdor** [comment]
Hi again! I managed to resolve it, it seemed it took a while for my foundry server to adopt to the new changes in the css after the initial update, could have been cache or something else, even though I tried incognito.  Thanks for replying!

**Comment by TheEpicSnowWolf** [comment]
That's great to hear, glad that everything works properly now! :)
