### ISSUE TITLE
How to use this styling without editting core css file

### ISSUE THREAD

**Issue by jbblily** [TheEpicSnowWolf/Foundry-VTT-Prettier-Login-Screen#7]
Hello, I just want to let you know how to use this styling without editting core css file.

You can just include this css file into your core localization module.

Here's how to make localization module.

It is pretty simple. just add one line to your module.json - "coreTranslation":true

In that way, you can apply css to your core application.

Anyways, thank you for your hard work!

**Comment by TheEpicSnowWolf** [comment]
Hi @jbblily, sorry for the late response. Would you mind elaborating further on this? As far as I am aware, modules can only inject CSS or JS in the game session and not on setup or login pages.

**Comment by jbblily** [comment]
Cool, I don't mind. It's actually not a big deal.. I just found it out when I make my own translation module.

The problem is, if a user's preferred language is not English (and this person is using core translation module), this will not work. 

In that case, the only way is to manually add css file to the module. 

If you don't mind this, I can help with you, probably...

**Comment by jbblily** [comment]
Hey I made a simple module for this, so if you are interested in this, you can first try and then comment to me. I will contribute on your project by pull request. 

https://github.com/jbblily/Foundry-VTT-Prettier-Login-Screen/tree/jbblily-patch-1

**Comment by TheEpicSnowWolf** [comment]
Ah, thanks, I see what you mean by localisation module now. This is indeed an interesting workaround for getting this applied and have it unaffected by a coreupdate. I can see that in your most recent commits you include only the "text title version" of the CSS, I would suggest having the module really only act as a wrapper for the standard file, and then have the user edit the login CSS as normal to decide which version they want to use. However, feel free to open a PR and we can discuss/adjust files there.

**Comment by jbblily** [comment]
I deleted title image version on purpose (to show you how it works immediately)

I'm not native to English... Thank you for being generous to some communication mistakes 😄

I'll give you a PR then. Take it free.
